version: '3.8'

services:
  hercules-dbgate:
    container_name: hercules-dbgate
    image: dbgate/dbgate
    restart: always
    ports:
      - 8082:3000
    volumes:
      - hercules-dbgate-data:/root/.dbgate
    depends_on:
      - hercules-postgres
    environment:
      CONNECTIONS: con1

      LABEL_con1: Database_PG
      SERVER_con1: hercules-postgres
      USER_con1: ${DB_USER}
      PASSWORD_con1: ${DB_PASSWORD}
      PORT_con1: 5432
      ENGINE_con1: postgres@dbgate-plugin-postgres

volumes:
  hercules-dbgate-data:
